### ISSUE TITLE
Paginación

### ISSUE THREAD

**Issue by martincuba** [LeanCarp/PPS#13]
paginas en las tablas de grandes listados... ej alumnos y cursadas, puede ser tambien en foro

**Comment by LeanCarp** [comment]
agregado para cursadas

**Comment by martincuba** [comment]
Ver posibilidad de implementarlo en agregar multiples cursadas. El resto estarìa

**Comment by martincuba** [comment]
me cambia a la segunda pagina, cuando solo hay una sola pagina para mostrar.
![image](https://user-images.githubusercontent.com/22064088/46585570-edbf6680-ca48-11e8-9504-713088e77c86.png)

![image](https://user-images.githubusercontent.com/22064088/46585579-f9129200-ca48-11e8-97e1-5c0d66e2a0f1.png)

**Comment by LeanCarp** [comment]
Arreglado para multiples cursadas y materias. Lo agregamos a algún lado mas?
