### ISSUE TITLE
comision

### ISSUE THREAD

**Issue by martincuba** [LeanCarp/PPS#16]
- [x] En modificar, no carga la materia, y nose si esta "actualizando". al menos que la borre y cree una nueva.

- [ ] Un icono y una vista en la que se pueda ver los alumnos de la comisión.

- [x] Ver la posibilidad de sacar a comisión del menú configuración, y que sea de acceso directo, por la necesidad del frecuente acceso.

**Comment by LeanCarp** [comment]
El no carga la materia, puede ser porque esta cargado una materia que no coincide con la clave. Las claves son "id-nombreMateria" y en mi caso, no carga por "3-Simulación" es la comisión y la materia de id 3 yo le cambie el nombre. Fijate si ves lo mismo

**Comment by martincuba** [comment]
Encontré el error.  Además detecte que, cuando se cambia el nombre de la materia, se rompe la comisión ya que queda con los nombres viejos.
